### ISSUE TITLE
https://https//1995parham.me link broken!

### ISSUE THREAD

**Issue by BaseMax** [1995parham/1995parham.pdf#1]
Hi Parham;

I found a minor error in your CV file:
https://github.com/1995parham/1995parham.pdf/blob/main/main.tex#L24

**Comment by 1995parham** [comment]
Thanks for reporting it, you are right.

**Comment by 1995parham** [comment]
By the way, I want to say thanks to Github for the actions, they are awesome and I am switching all of my projects to it.

**Comment by BaseMax** [comment]
> By the way, I want to say thanks to Github for the actions, they are awesome and I am switching all of my projects to it.

Parham, Thanks for your feedback.

Yeah, I agree. `pre-commit`, `clang-format`, `spell checker`, `textlint` `super-linter`, `codeql-action`, `prettier`, autodeploy apps, and many good ideas are helping projects to fix problems sooner and keep projects in one common code style based. You can find some examples here: https://github.com/One-Language/One/tree/master/.github/workflows

These are just a few of the most popular. By the way, you can find everything you need at the marketplace: https://github.com/marketplace?type=actions

I see that robots today have a big role to play in helping companies keep libraries and dependencies up to date to safe versions.
